### ISSUE TITLE
Sync issue

### ISSUE THREAD

**Issue by achusat** [ivanmarincic/wear-documents#1]
It's unable to sync with Sony smartwatch 3

**Comment by ivanmarincic** [comment]
I cannot help you if no more information is provided. Please try this before doing anything else.

1. Check if you watch and phone are really connected( restarting both phone and watch will ensure this, if you are already connected over bluetooth and Wear OS app).
2. You have to install both applications from same source and they have to be on same version.
3. Try leaving app open when syncing.

If nothing of the above helps you need to provide me with information like steps you took, screenshots(or video), and document you are trying to sync.
